### ISSUE TITLE
Backbone changes 

### ISSUE THREAD

**Issue by abhigoku10** [yichen928/GEAL_active_learning#3]
@yichen928  thanks for sharing your source code 
Can we change the backbone from transformer dino to swin / vit or even cnn based backbone ?

**Comment by yichen928** [comment]
Hi thanks for your interest.
Apart from  DeiT-small (ViT-small) pretrained with DINO in this repo, we only tried supervised DeiT-small model.  You can see the comparison in our appendix. I think supervised pretraining would not lead to great performance. Since attention of transformers is used in our method, some modifications may be necessary to apply cnn backbones.
